"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, Pause, Play, Plus } from "lucide-react";
import { track, visitContext, createId } from "@/lib/analytics";

const examples = [
  { name: "Your brief", need: "A missing piece.", provider: "A relevant business.", criteria: ["The requirement", "The location", "The timing"], detail: "Start with what you need to make happen. The brief shapes the search, whatever your industry.", curve: 0 },
  { name: "Expertise", need: "Someone who knows.", provider: "The right experience.", criteria: ["Relevant experience", "Scope of the work", "Required timing"], detail: "A challenge your team cannot solve alone. An introduction starts with the experience and support you need.", curve: -34 },
  { name: "Capacity", need: "Room to do more.", provider: "Capacity to help.", criteria: ["Work to be delivered", "Available capacity", "Delivery requirements"], detail: "More work than your team can take on. Find a business equipped to help you deliver it.", curve: 36 },
  { name: "Supply", need: "A reliable source.", provider: "A suitable supplier.", criteria: ["Product or service", "Volume and scope", "Location and lead time"], detail: "A new source of products, materials or services. Your requirements define which suppliers make sense.", curve: -16 },
];
const questions = [
  ["What am I paying for?", "A relevant business introduction. I agree the scope and fee with you before making a paid introduction. There is no payment to submit a brief. Any products, services or further work are agreed separately with the business you meet."],
  ["How quickly can you find someone?", "It depends on your requirements, location and the other business’s availability. Share your deadline so I can assess what is realistic. I check timing with the business before an introduction; submitting a brief does not guarantee a match."],
  ["Do you work in my industry?", "I consider briefs across industries. The examples here illustrate types of business need, rather than a fixed list of services. Tell me what you need and I’ll assess whether I can help with a relevant introduction."],
  ["Do you work with businesses outside the US?", "Yes. My primary focus is businesses in the United States, and I also arrange introductions worldwide. Share the location or market you need to cover so I can assess the fit."],
  ["What happens after I submit my brief?", "I review your requirements and reply by email to clarify the brief and discuss whether I can help. If there is a relevant opportunity, we agree the introduction scope, fee and what information to share before connecting."],
  ["Can I offer my business’s services?", "Yes. Use ‘Offer your services’ below to share what you do, where you operate and your availability. I use those details to assess potential introductions. Submitting your details does not guarantee work."],
];
function Mark() { return <svg width="32" height="32" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M4 5v22M28 5v22M4 16h24M10 5v6m12 10v6" stroke="currentColor" strokeWidth="3.5" /></svg>; }

function ConnectionField() {
  const [selected, setSelected] = useState(0), [paused, setPaused] = useState(false), [visible, setVisible] = useState(true);
  const field = useRef<HTMLDivElement>(null);
  const example = examples[selected];
  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => setVisible(entry.isIntersecting), { threshold: .05 });
    if (field.current) observer.observe(field.current);
    const visibility = () => setVisible(!document.hidden && !!field.current && field.current.getBoundingClientRect().bottom > 0 && field.current.getBoundingClientRect().top < window.innerHeight);
    document.addEventListener("visibilitychange", visibility);
    return () => { observer.disconnect(); document.removeEventListener("visibilitychange", visibility); };
  }, []);
  const path = (offset: number) => `M -80 ${200 + offset * 1.45} C 190 ${200 + offset * 1.2}, 280 ${90 + offset * .5 + example.curve}, 420 ${150 + offset * .5 + example.curve} S 550 ${250 - offset * .3}, 600 200 S 680 ${115 + offset * .3 - example.curve}, 800 ${150 + offset * .5 - example.curve} S 1050 ${200 + offset * 1.3}, 1280 ${200 + offset * 1.45}`;
  return <div className={`connection-experience ${paused || !visible ? "paused" : ""}`} ref={field}>
    <div className="field-controls"><span className="small-label">EXPLORE A BUSINESS NEED</span><div className="sector-buttons" role="group" aria-label="Illustrative business needs">{examples.map((item, i) => <button key={item.name} aria-pressed={selected === i} className={selected === i ? "active" : ""} onClick={() => { setSelected(i); track("example_select", item.name.toLowerCase()); }}>{item.name}<span aria-hidden="true">↗</span></button>)}</div><button className="motion-toggle" aria-label={paused ? "Play animation" : "Pause animation"} aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? <Play size={16} /> : <Pause size={16} />}</button></div>
    <div className="connection-field" onPointerMove={e => { if (paused || e.pointerType !== "mouse" || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; const bounds = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty("--drift", `${((e.clientX - bounds.left) / bounds.width - .5) * 10}px`); }} onPointerLeave={e => e.currentTarget.style.setProperty("--drift", "0px")}>
      <div className="field-top"><span>FROM A SPECIFIC NEED TO A USEFUL INTRODUCTION</span><span>AN ILLUSTRATION</span></div>
      <div className="line-drift"><svg key={selected} className="connection-lines" viewBox="0 0 1200 400" fill="none" aria-hidden="true" preserveAspectRatio="xMidYMid slice"><g className="possible-paths">{Array.from({ length: 23 }, (_, i) => <path key={i} d={path((i - 11) * 13)} stroke="currentColor" strokeWidth=".8" opacity={.13 + Math.abs(i - 11) * .015} />)}</g><path className="chosen-path" d={path(0)} pathLength="1" stroke="currentColor" strokeWidth="1.8" /><path className="travelling-signal" d={path(0)} pathLength="1" stroke="currentColor" strokeWidth="4" strokeLinecap="round" /></svg></div>
      <div className="field-caption field-caption-left"><span>01 / YOUR BUSINESS</span><strong>You need.</strong><p key={example.need}>{example.need}</p></div><div key={`center-${selected}`} className="connection-center"><Mark /><span>The introduction</span></div><div className="field-caption field-caption-right"><span>02 / THE RELEVANT BUSINESS</span><strong>They help.</strong><p key={example.provider}>{example.provider}</p></div>
      <div className="field-bottom" key={`criteria-${selected}`}>{example.criteria.map((criterion, i) => <span key={criterion} style={{ animationDelay: `${i * 70 + 180}ms` }}><span className="criterion-number">0{i + 1}</span>{criterion}</span>)}</div>
    </div><div className="field-explanation" aria-live="polite"><p key={selected}>{example.detail}</p><span>Every introduction starts with a brief.</span></div>
  </div>;
}
type Brief = { details: string; timing: string; location: string; name: string; email: string; company: string; website: string };
const emptyBrief: Brief = { details: "", timing: "", location: "", name: "", email: "", company: "", website: "" };

export default function Home() {
  const [mode, setMode] = useState<"need" | "supply">("need"), [step, setStep] = useState(1), [brief, setBrief] = useState<Brief>(emptyBrief), [status, setStatus] = useState("idle"), [error, setError] = useState("");
  const [faq, setFaq] = useState<number | null>(null), [sticky, setSticky] = useState(false), [reference, setReference] = useState("");
  const requestId = useRef(""), started = useRef(false);
  const formHeading = useRef<HTMLHeadingElement>(null), successHeading = useRef<HTMLHeadingElement>(null), hero = useRef<HTMLElement>(null), contact = useRef<HTMLElement>(null);
  useEffect(() => {
    requestId.current = createId(); track("page_view", "home");
    const updateSticky = () => { if (hero.current && contact.current) setSticky(hero.current.getBoundingClientRect().bottom < 0 && contact.current.getBoundingClientRect().top > window.innerHeight); };
    const observer = new IntersectionObserver(updateSticky, { threshold: [0, .01] });
    if (hero.current) observer.observe(hero.current); if (contact.current) observer.observe(contact.current);
    window.addEventListener("resize", updateSticky);
    return () => { observer.disconnect(); window.removeEventListener("resize", updateSticky); };
  }, []);
  useEffect(() => { if (status === "success") successHeading.current?.focus(); }, [status]);
  useEffect(() => { if (step === 2) formHeading.current?.focus(); }, [step]);
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const elements = document.querySelectorAll<HTMLElement>(".introduction-example, .portrait");
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { (entry.target as HTMLElement).dataset.reveal = "shown"; observer.unobserve(entry.target); }
    }), { threshold: .12 });
    elements.forEach(element => { if (element.getBoundingClientRect().top > window.innerHeight) { element.dataset.reveal = "ready"; observer.observe(element); } });
    return () => observer.disconnect();
  }, []);
  function chooseMode(next: "need" | "supply") { setMode(next); setStep(1); setError(""); if (status === "success") { setBrief(emptyBrief); setStatus("idle"); requestId.current = createId(); started.current = false; } }
  function startForm() { if (!started.current) { track("form_start", mode); started.current = true; } }
  function update(field: keyof Brief, value: string) { setBrief(previous => ({ ...previous, [field]: value })); }
  function cta(place: string) { chooseMode("need"); track("cta_click", place); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (status === "sending") return;
    if (step === 1) { setStep(2); track("brief_continue", mode); requestAnimationFrame(() => formHeading.current?.focus()); return; }
    setStatus("sending"); setError("");
    try { const response = await fetch("/api/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...brief, mode, id: requestId.current, ...visitContext() }) }); const body = await response.json() as { error?: string; reference?: string }; if (!response.ok) throw new Error(body.error || "Please try again."); setReference(body.reference || ""); setStatus("success"); }
    catch (failure) { setStatus("idle"); setError(failure instanceof Error ? failure.message : "I couldn’t save your brief. Please try again."); }
  }
  return <><a className="skip" href="#main">Skip to content</a><header className="nav wrap"><a href="#" className="brand" aria-label="Humza Sheikh home"><Mark /><span>Humza Sheikh<small>Business introductions</small></span></a><nav aria-label="Main navigation"><a href="#how-it-works">The approach</a><a href="#about">About Humza</a><a className="nav-cta" href="#request" onClick={() => cta("header")}>Describe your need <ArrowUpRight size={17} /></a></nav></header>
    <main id="main"><section className="hero wrap" ref={hero}><div className="eyebrow"><span>INDEPENDENT BUSINESS INTRODUCTIONS</span><span>US FOCUS. WORLDWIDE CONNECTIONS.</span></div><div className="hero-heading"><h1>The right people.<br /><span>Right when it matters.</span></h1><div className="hero-intro"><p>I connect businesses across the US and worldwide with relevant providers. Tell me what you need, where and by when. The introduction fee is agreed beforehand.</p><a href="#request" className="button dark" onClick={() => cta("hero")}>Describe your need <ArrowUpRight size={20} /></a><a href="#about" className="founder-inline"><img src="/founder.jpg" alt="" width="40" height="40" /><span>A personal introduction.<br /><strong>Humza Sheikh · Business introductions</strong></span></a></div></div><ConnectionField /></section>
    <section className="introduction-section wrap section-grid" id="the-introduction"><div className="section-label">01 / THE INTRODUCTION</div><div><div className="section-heading"><h2>A conversation<br />worth having.</h2><p>Knowing who to speak to is useful.<br />Knowing why you’re speaking is where the value starts.</p></div><div className="introduction-example"><div className="example-brief"><span className="small-label">AN ILLUSTRATIVE BRIEF</span><h3>“We need a delivery partner for a project starting next month.”</h3><p>A defined requirement. A deadline. A business with work to move forward.</p><div className="brief-annotation"><span>YOUR STARTING POINT</span><ArrowRight size={22} /></div></div><div className="example-intro"><div className="example-intro-header"><Mark /><span>THE INTRODUCTION, WITH CONTEXT</span></div><h3>Here’s why this<br />conversation makes sense.</h3><dl><div><dt>The requirement</dt><dd>The work, location and deadline are clear.</dd></div><div><dt>The reason for the fit</dt><dd>Relevant experience, interest and availability are discussed.</dd></div><div><dt>The next conversation</dt><dd>Both sides know what to explore and what still needs agreeing.</dd></div></dl><span className="example-disclaimer">An example of the approach, not a completed client engagement.</span></div></div></div></section>
    <section className="approach-section" id="how-it-works"><div className="wrap section-grid"><div className="section-label">02 / THE APPROACH</div><div><h2>Your brief.<br />A focused search.<br /><span>A considered introduction.</span></h2><div className="steps">{[["01", "Tell me what matters", "The need, the deadline and the details that would make a provider right for you."], ["02", "I explore the fit", "Focused research and direct conversations to check relevance, interest and availability."], ["03", "We agree, then connect", "You understand the proposed introduction and agree the fee before I connect you."]].map(([number, title, copy]) => <article key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="commercial-note"><p><strong>A fee per introduction.</strong> No payment to submit a brief.</p><a className="text-link" href="#request" onClick={() => cta("approach")}>Describe your need <ArrowUpRight size={18} /></a></div></div></div></section>
    <section className="about-section wrap" id="about"><div className="portrait"><img src="/founder.jpg" alt="Humza Sheikh" width="800" height="800" loading="lazy" /><span>HUMZA SHEIKH / FOUNDER</span></div><div className="about-copy"><div className="section-label">03 / THE PERSON BEHIND THE CONNECTION</div><h2>Business is personal.<br />So is the introduction.</h2><p>I’m Humza. I build businesses and the systems behind them. That work has taught me how much progress depends on finding someone who understands the problem and can help solve it.</p><p>My business is based in London and serves companies across the US and worldwide. I combine research, technology and direct conversations to find relevant connections across industries.</p><p className="about-statement">You bring the business need.<br />I give the search a clear direction.</p><a className="text-link" href="https://www.linkedin.com/in/humza-sheikh-/" target="_blank" rel="noreferrer">Explore my background on LinkedIn <ArrowUpRight size={18} /></a></div></section>
    <section className="faq-section wrap section-grid"><div className="section-label">A FEW THINGS TO KNOW</div><div>{questions.map(([question, answer], i) => <div className={`faq ${faq === i ? "open" : ""}`} key={question}><h3><button onClick={() => setFaq(faq === i ? null : i)} aria-expanded={faq === i} aria-controls={`answer-${i}`} id={`question-${i}`}>{question}<Plus size={20} /></button></h3><div className="faq-answer" id={`answer-${i}`} role="region" aria-labelledby={`question-${i}`} aria-hidden={faq !== i}><div><p>{answer}</p></div></div></div>)}</div></section>
    <section className="contact-section" id="request" ref={contact}><div className="wrap contact-inner"><div className="contact-copy"><div className="section-label">04 / YOUR NEXT CONNECTION</div><h2>{mode === "need" ? <>What’s the<br />missing piece?</> : <>What can your<br />business offer?</>}</h2><p>{mode === "need" ? "Whether you’re in the US or elsewhere, start with the problem you need to solve. A few useful details give the search a clear starting point." : "Share your services, the markets you cover and your availability. Providers worldwide are welcome."}</p><div className="next-steps"><span className="small-label">WHAT HAPPENS NEXT</span><p>I review your brief and reply by email to discuss fit and the next step. Any introduction fee is agreed with you beforehand.</p></div><a className="email-link" href="mailto:humza@humzasheikh.com">humza@humzasheikh.com <ArrowUpRight size={18} /></a><button className="provider-link" onClick={() => { chooseMode(mode === "need" ? "supply" : "need"); track("cta_click", mode === "need" ? "provider" : "buyer"); }}>{mode === "need" ? "Here to help another business? Offer your services" : "Looking for a provider? Describe your need"}<ArrowRight size={16} /></button></div>
    <div className="form-container">{status === "success" ? <div className="success" role="status"><span className="success-check"><Check size={28} /></span><span className="small-label">BRIEF RECEIVED{reference ? ` / ${reference}` : ""}</span><h3 tabIndex={-1} ref={successHeading}>Your brief<br />is with me.</h3><p>I’ll review your requirements and reply to <strong>{brief.email}</strong> to discuss whether I can help. No introduction fee has been charged.</p><p className="success-followup">Need to add something? Email me and include your reference.</p><a className="text-link" href={`mailto:humza@humzasheikh.com?subject=${encodeURIComponent(`My introduction brief ${reference}`)}`}>Add a detail by email <ArrowUpRight size={18} /></a><button className="provider-link" onClick={() => { setBrief(emptyBrief); setStep(1); setStatus("idle"); started.current = false; requestId.current = createId(); }}>Send another brief <ArrowRight size={16} /></button></div> : <form onSubmit={submit} onFocus={startForm} aria-busy={status === "sending"}>
      <div className="form-progress"><span>0{step} / 02</span><span>{step === 1 ? "THE BRIEF" : "YOUR DETAILS"}</span><div aria-hidden="true"><i className="filled" /><i className={step === 2 ? "filled" : ""} /></div></div><h3 ref={formHeading} tabIndex={-1}>{step === 1 ? (mode === "need" ? "What would move things forward?" : "Where can you make a difference?") : "Where should I get back to you?"}</h3>
      <div key={`${step}-${mode}`} className="form-step">{step === 1 ? <><label>{mode === "need" ? "What does your business need?" : "What can your business offer?"}<textarea name="details" value={brief.details} onChange={event => update("details", event.target.value)} required minLength={15} maxLength={4000} rows={3} placeholder={mode === "need" ? "The challenge, the kind of help you need and any must-haves…" : "Your services, products or expertise, and the businesses you can help…"} /></label><div className="form-row"><label>{mode === "need" ? "When do you need it?" : "When are you available?"}<input name="timing" value={brief.timing} onChange={event => update("timing", event.target.value)} required maxLength={180} placeholder="A date or timeframe" /></label><label>{mode === "need" ? "Where do you need it?" : "Where do you operate?"}<input name="location" value={brief.location} onChange={event => update("location", event.target.value)} required maxLength={180} placeholder="City, state or country" autoComplete="off" /></label></div></> : <><div className="brief-recap"><span>{mode === "need" ? "YOUR REQUIREMENT" : "YOUR OFFER"}</span><p>{brief.details}</p><small>{brief.location} · {brief.timing}</small><button type="button" onClick={() => setStep(1)}>Edit brief</button></div><div className="form-row"><label>Your name<input name="name" value={brief.name} onChange={event => update("name", event.target.value)} autoComplete="name" required maxLength={120} placeholder="Full name" /></label><label>Work email<input name="email" type="email" value={brief.email} onChange={event => update("email", event.target.value)} autoComplete="email" required maxLength={254} placeholder="you@company.com" /></label></div><label>Company<input name="company" value={brief.company} onChange={event => update("company", event.target.value)} autoComplete="organization" required maxLength={160} placeholder="Business name" /></label><p className="privacy-note">I use your details to assess and respond to your request. We agree what to share with another business before an introduction.</p></>}</div>
      <div className="honey" aria-hidden="true"><label>Leave this empty<input name="website" value={brief.website} onChange={event => update("website", event.target.value)} tabIndex={-1} autoComplete="off" /></label></div>{error && <p className="form-error" role="alert">{error} You can also <a href="mailto:humza@humzasheikh.com">email me directly</a>.</p>}<button type="submit" className="button dark submit" disabled={status === "sending"}>{status === "sending" ? "Sending your brief…" : step === 1 ? "Continue to your details" : "Send your brief"}<ArrowRight size={20} /></button><div className="form-bottom">{step === 2 && <button className="back-link" type="button" disabled={status === "sending"} onClick={() => setStep(1)}><ArrowLeft size={14} />Back</button>}<p>No payment to submit. Fee agreed before an introduction.</p></div>
    </form>}</div></div></section></main>
    <footer className="wrap footer"><a className="brand" href="#"><Mark /><span>Humza Sheikh<small>Business introductions · Worldwide</small></span></a><p>One introduction can change what’s next.</p><a href="https://www.linkedin.com/in/humza-sheikh-/" target="_blank" rel="noreferrer">LinkedIn ↗</a><small>© {new Date().getFullYear()} Humza Sheikh</small></footer><div className={`mobile-cta ${sticky ? "visible" : ""}`} aria-hidden={!sticky} inert={!sticky}><a href="#request" className="button dark" onClick={() => cta("mobile_sticky")}>Describe your need<ArrowUpRight size={20} /></a></div>
  </>;
}
