/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false` (hash: 76c030ac0269ecb3d976c74733121a1c)
interface __BaseEnv_Env {
	DB: D1Database;
	OWNER_EMAIL: "humza@humzasheikh.com";
	NOTIFICATION_FROM: "Humza Sheikh <humza@humzasheikh.com>";
	ACCESS_AUD: "00243432262046129eb1461840d95f888af3ee733fcc3e43dfd7f74b6e32ff23";
	ACCESS_TEAM_DOMAIN: "humza-sheikh-admin.cloudflareaccess.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OWNER_EMAIL" | "NOTIFICATION_FROM" | "ACCESS_AUD" | "ACCESS_TEAM_DOMAIN">> {}
}

